structure myGrammar = Grammar
(* val t = myGrammar.addToken "$"
val t = myGrammar.addToken "+"
val t = myGrammar.addToken "*"
val t = myGrammar.addToken "N"
val t = myGrammar.addSymbol "S"
val t = myGrammar.addSymbol "E"
val t = myGrammar.addSymbol "E'"
val t = myGrammar.addSymbol "T"
val t = myGrammar.addSymbol "T'"
val t = myGrammar.addRule "S" [["E", "$"]]
val t = myGrammar.addRule "E" [["T", "E'"]]
val t = myGrammar.addRule "E'" [["+", "T", "E'"], []]
val t = myGrammar.addRule "T" [["N", "T'"]]
val t = myGrammar.addRule "T'" [["*", "N", "T'"], []] *)

val t = myGrammar.addToken "a"
val t = myGrammar.addToken "b"
val t = myGrammar.addSymbol "C"
val t = myGrammar.addSymbol "A"
val t = myGrammar.addSymbol "B"
val t = myGrammar.addSymbol "D"
val t = myGrammar.addRule "C" [["D", "A"]]
val t = myGrammar.addRule "A" [["a", "A"]]
val t = myGrammar.addRule "B" [["b", "B"], []]
val t = myGrammar.addRule "D" [["B", "B"]]

(* val x = myGrammar.addSymbol "A";
val x = myGrammar.addSymbol "B";
val x = myGrammar.addSymbol "C";
val x = myGrammar.addSymbol "D";
val x = myGrammar.addToken "a";
val x = myGrammar.addRule "A" [["B"]];
val x = myGrammar.addRule "B" [["C"]];
val x = myGrammar.addRule "C" [["D"]];
val x = myGrammar.addRule "D" [["a"]]; *)